######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 29 16:02:32 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../src/AnalyzeParameters.h ../src/HtmlCreator.h
SOURCES += test_AnalyzeParameters.cpp \
           test_HtmlCreator.cpp \
           ../src/AnalyzeParameters.cpp \
           #../src/HtmlCreator.cpp
